// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'eb54ab5ea0c14d3ca6bc64f7a001b8e0',
    appId: '1:984203255055:android:74763fe82cafed868a727a',
    messagingSenderId: '984203255055',
    projectId: 'final-project-flutter-expert',
    storageBucket: 'final-project-flutter-expert.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'eb54ab5ea0c14d3ca6bc64f7a001b8e0',
    appId: '1:984203255055:ios:74763fe82cafed868a727a',
    messagingSenderId: '984203255055',
    projectId: 'final-project-flutter-expert',
    storageBucket: 'final-project-flutter-expert.appspot.com',
    iosClientId: '984203255055-shdtk183nsdhjqmgpg53mohuuf6r9d90.apps.googleusercontent.com',
    iosBundleId: 'com.ditonton.ditonton"',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'eb54ab5ea0c14d3ca6bc64f7a001b8e0',
    appId: '1:984203255055:web:74763fe82cafed868a727a',
    messagingSenderId: '984203255055',
    projectId: 'final-project-flutter-expert',
    authDomain: 'final-project-flutter-expert.firebaseapp.com',
    storageBucket: 'final-project-flutter-expert.appspot.com',
    measurementId: 'G-Y475Z5MPVH',
  );

}
